set SPACEFISH_PROMPT_ADD_NEWLINE false

set SPACEFISH_VI_MODE_NORMAL [CMD]
set SPACEFISH_VI_MODE_INSERT [INS]
set SPACEFISH_VI_MODE_VISUAL [VIS]
set SPACEFISH_VI_MODE_REPLACE_ONE [RPL]
set SPACEFISH_VI_MODE_COLOR black
set SPACEFISH_VI_MODE_SHOW true

set SPACEFISH_JOBS_SHOW true
set SPACEFISH_JOBS_SYMBOL \&

set SPACEFISH_USER_PREFIX 
set SPACEFISH_USER_SUFFIX 
set SPACEFISH_USER_SHOW always

set SPACEFISH_HOST_PREFIX @
set SPACEFISH_HOST_SHOW always

set SPACEFISH_CHAR_SYMBOL \$

set SPACEFISH_PROMPT_ORDER vi_mode dir git jobs line_sep user host char
