noh
set nocompatible
set noswapfile
filetype plugin on
set autoread
syntax on
set title

set hidden
set wildmenu
set showmode
set showcmd
set hlsearch

set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set ruler
set showmatch
set cmdheight=1
set laststatus=2
set confirm
set visualbell
set scrolloff=6

set number relativenumber
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
augroup END

set cursorline
hi CursorLine term=bold cterm=bold ctermbg=NONE

"highlight characters beyond col. 80
match Error /\%>81c/

set shiftwidth=4
set tabstop=4
set smarttab
set expandtab

"set statusline=%1*\ file\ %3*\ %f\ %4*\ 
set statusline+=%=\ 
set statusline+=%3*\ %c\.%l\ of\ %L\ %2*\ %f\ 

colorscheme paramount

hi user1 ctermbg=3 ctermfg=0
hi user2 ctermbg=3 ctermfg=0
hi user3 ctermbg=7 ctermfg=NONE
hi user4 ctermbg=NONE ctermfg=NONE
hi group1 ctermbg=NONE ctermfg=0

hi statusline ctermbg=15 ctermfg=NONE
hi statuslinenc ctermbg=15 ctermfg=0

hi vertsplit ctermbg=15 ctermfg=3
"set fillchars+=vert:\│
set fillchars+=vert:\ 

highlight Normal guibg=NONE ctermbg=NONE

highlight NonText ctermfg=231

""" Word replacements e.g. Theta -> θ
" iabbrev Theta <C-k>Wθ
" iabbrev theta <C-k>Wθ
" iabbrev Omega <C-k>WΩ
" iabbrev omega <C-k>Wω

""" automatically compile markdown on save

autocmd BufWritePost *.md !pandoc % -s -o %:r.pdf && open -a Skim.app %:r.pdf


""" Plugins (junegunn/vim-plug)
call plug#begin()
    Plug 'godlygeek/tabular'
    Plug 'plasticboy/vim-markdown'
    Plug 'jiangmiao/auto-pairs'
    Plug 'junegunn/goyo.vim'
    Plug 'Yggdroot/indentLine'
call plug#end()

filetype plugin indent on

"## Plugin Settings
let g:vim_markdown_folding_disabled = 1 """ Vim Markdown

let g:indentLine_setColors = 1
let g:indentLine_char = '│'
let g:indentLine_first_char = '│'
let g:indentLine_color_term = 239

filetype indent on
